### ISSUE TITLE
Add confidence interval to experiment reports

### ISSUE THREAD

**Issue by geisserf** [prost-planner/prost#100]
We would like to compute the confidence interval of the expected average reward and show it in the report.

**Comment by geisserf** [comment]
I read through multiple sources and tutorials over the past days and came to the conclusion that we want the empirical bootstrap based confidence interval. Since some of our reward distributions can be heavy tailed we should apparently use the studentized bootstrap, or bootstrap-t.

An example for a heavy tailed distribution is the distribution of wealth over population in a country, where most of the wealth belongs to 0.1% of the population. We have a similar case with the push-your-luck domain, where very few samples will have an exponentially larger reward than most of the samples.

Some literature for bootstrap confidence intervals:

[Short Introduction, MIT](https://ocw.mit.edu/courses/mathematics/18-05-introduction-to-probability-and-statistics-spring-2014/readings/MIT18_05S14_Reading24.pdf)
[More detailed introduction, CMU](http://www.stat.cmu.edu/~cshalizi/402/lectures/08-bootstrap/lecture-08.pdf)
[Examples of when bootstrap should not be used](https://notstatschat.tumblr.com/post/156650638586/when-the-bootstrap-doesnt-work)

Currently I use [this python library](https://pypi.org/project/bootstrapped/) to compute the confidence interval via bootstrapping, but I have to confirm that this is actually bootstrap-t (from an initial look it should be). It is under the hood of [Facebook incubator](https://github.com/facebookincubator/) but I have no idea what that is.

**Comment by thomaskeller79** [comment]
Great work @geisserf! I really enjoyed reading the short introduction and will look into the more detailed one when I find some more time. From what I can say so far, this is exactly what we have been looking for.

Is bootstrap-t the bootstrap percentile method that should *not* be used according to the MIT introduction?

**Comment by geisserf** [comment]
No, bootstrap-t is the "studentized" bootstrap that should be used if it is possible that distributions have heavy tails. I think the one that should *not* be used is called percentile-based bootstrap or similar.

**Comment by thomaskeller79** [comment]
I was mislead by the fact that it's also called the percentile-t bootstrap.

Still, does bootstrap-t make sense? I believe there are no heavy tails in our scenario with a discrete distribution with finite support.

**Comment by geisserf** [comment]
An example for a heavy tailed distribution is the distribution of wealth over population in a country, where most of the wealth belongs to 0.1% of the population. I think we have a similar case with the push-your-luck domain, where very few samples will have an exponentially larger reward than most of the samples.

**Comment by thomaskeller79** [comment]
This sounds reasonable, but I'm not 100% convinced yet. I wanted to see how large the differences are and wrote a small script (using your code for the percentile-t bootstrap in function f1). If you just run it it computes confidence intervals with the percentile-t bootstrap and the empirical bootstrap for 2 examples, and you will see that the differences are quite significant.

[ci.zip](https://github.com/prost-planner/prost/files/4323016/ci.zip)

**Comment by geisserf** [comment]
I don't understand, why does it mean that we do not have heavy tailed distributions if the two bootstrap implementations give significant different results?

**Comment by thomaskeller79** [comment]
We certainly don't have heavy tails in all the domains, so the question is if we should use the percentile-t bootstrap for the computation of all confidence intervals. As I believe that we don't have heavy tails in any domain except possibly push you luck, I don't think we should use it anywhere else as the resulting CIs are very different.

The script is only to test how significant the differences are (if the CIs were almost identical, I wouldn't have minded).

**Comment by geisserf** [comment]
I am a bit confused on why you call the studentized bootstrap percentile bootstrap. Looking at the implementation it does not seem to be the studentized pseudocode given in http://www.stat.cmu.edu/~cshalizi/402/lectures/08-bootstrap/lecture-08.pdf on page 8, or am I wrong?

**Comment by thomaskeller79** [comment]
I'm calling the studentized bootstrap the percentile-t bootstrap just as you did in the second post and until the fourth post of this issue.

I cannot say anything about the implementation of the studentized bootstrap as I didn't implement it. I took it from your implementation in reward_confidence_interval.py.

**Comment by geisserf** [comment]
Maybe let's have a brief Skype meeting on this topic.

**Comment by thomaskeller79** [comment]
If you use the result of IPC2014 configuration on navigation 1 (where it only executes the optimal policy) in the script:

all_rews = [-8] * 96 + [-40] * 4

you get the following CIs:

studentized bootstrap: (-9.29, -9.05)
empirical bootstrap: (-10.56, -8.32)

**Comment by thomaskeller79** [comment]
@geisserf I proposed in a pull request to use the prostlab issue tracker for issues with prostlab rather than this one (I know that we said at some point that we might stick with just one issue tracker, but I don't really see the advantage now that things are nicely separated). If we agree on using the prostlab issue tracker, I believe we should move this issue there.

**Comment by geisserf** [comment]
@thomaskeller79 I agree, you can move this issue into the prostlab issue tracker.

**Comment by thomaskeller79** [comment]
The issue is not resolved yet, but it has been moved to the prostlab issue tracker where it is now [issue-1](https://github.com/prost-planner/prostlab/issues/1).
