### ISSUE TITLE
Wrong description of THTS' -ndn parameter?

### ISSUE THREAD

**Issue by GCrispino** [prost-planner/prost#105]
Hi!

PROST's usage details say indicates that the default value for the number of previously unvisited decision nodes that are expanded per trial (the `-ndn` command line parameter) is the horizon of the task:

```
  -ndn <int|H>                                                                                                          
    This is the parameter that describes the trial length ingredient. It specifies the number of previously unvisited de
cision nodes that is expanded before the trial length is considered sufficient.                                         
    Default: Horizon of task                                                                                            
```

However, in the code it looks like the default is actually 1, as it can be seen on https://github.com/prost-planner/prost/blob/master/src/search/thts.cc#L44:
```c++
...
      numberOfNewDecisionNodesPerTrial(1),
...
```
Am I not getting this or there's something wrong indeed?

**Comment by thomaskeller79** [comment]
Thanks @GCrispino for detecting this false documentation. I've fixed this in commit 474039c8d5e0053fb00d855213ea60f78810538a.
