### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by thomaskeller79** [prost-planner/prost#106]
We would like to add a license to the planner

**Comment by geisserf** [comment]
I think it would be good if we have a list of common licenses and how they are used / what the differences are / advantages / disadvantages. Maybe someone would like to volunteer to make such a list and we discuss it next week at the meeting?

**Comment by thomaskeller79** [comment]
That would certainly be a good idea, but who wants to dig voluntarily into the world of software licenses? [Here](https://choosealicense.com/licenses/) is a quite compact overview that might help us to make a decision.

**Comment by mejrpete** [comment]
Hi all --- found this when I went to check whether there was an existing license chosen for PROST. I've been experimenting with PROST for a research project (which is an industry partnership) and wanted to have my ducks in a row regarding licenses for all the tools that are being explored.

Not intending to clutter your issue tracker. Just wanted to indicate that there is also active outside interest on what the license is likely to look like for PROST!

**Comment by geisserf** [comment]
Hi Peter,
Thank you for your comment, we are happy to hear that other people are also interested in this topic! Both Thomas and I have worked with industry partners in previous research projects as well and we know that the software license often can make the difference whether to use an existing system or make one from scratch. Being able to use (parts of) PROST for industry related projects is an important aspect that we definitely want to support.

While this is not yet set in stone, after our latest meeting we are considering using the MIT license for PROST, which should cover such industry related concerns.

**Comment by thomaskeller79** [comment]
@mejrpete I'm not sure you'll be notified of the commit of @geisserf since he didn't mention your user name here, so I'm doing so in this post. We are very interested in your opinion on this topic. Would the MIT license suit your needs?

**Comment by mejrpete** [comment]
@geisserf @thomaskeller79 thank you both for the quick response! I believe the MIT license is absolutely suitable for my needs. It's for exactly the reasons you guys mention that folks in my lab also tend to use it for most releases.

Thanks again. I'll keep my eyes out for when a license is officially attached to make sure local copies get updated from the upstream accordingly!

**Comment by geisserf** [comment]
Once we commit to a license we also have to update the installation instructions in the README which currently refers to this issue.

**Comment by gobattiston** [comment]
Any updates on this?

**Comment by thomaskeller79** [comment]
We have a sprint planned for next week and even though we want to focus on scientific issues I'll propose to resolve this one as well.

**Comment by thomaskeller79** [comment]
In the sprint meeting today, we determined the following subtasks:

- [ ] deal with licensing issue regarding strxml files
- [ ] deal with licensing issue regarding state hash function
- [ ] move base64 implementation to ext folder (which will be excluded from license)
- [ ] update README
- [ ] determine year and copyright holders in license file
- [ ] update wiki

**Comment by thomaskeller79** [comment]
We decided to move the state hash function to its own file which we exclude from the license and open a new issue to implement our own hash function for states.

**Comment by thomaskeller79** [comment]
We decided not to introduce the `src/search/ext` folder because we'd like to mirror the namespace structure in the directory structure one day. Instead, we'll list all files that are excluded from the license.

**Comment by thomaskeller79** [comment]
Here are the experimental results:

https://ai.dmi.unibas.ch/_tmp_files/tkeller/issue-106-default.html
https://ai.dmi.unibas.ch/_tmp_files/tkeller/issue-106-all.html

The overall average reward looks horrible at first glance, but closer inspection shows it's mostly due to push your luck. IPC score for ipc2014 configuration on the other hand looks very good, but I actually believe this is mostly noise. Judging from the trials in the first relevant state, I'd say that planner performance is pretty much the same as before (which is what we aimed for) and I don't see any reason in the experiments that should prevent us from merging this issue.

**Comment by geisserf** [comment]
I agree.

**Comment by thomaskeller79** [comment]
As final steps, I have updated the wiki (github indeed detected the license automatically).

The issue has been closed with commit f247938b83511e4daf7a9763c49dfd8620ae56d4.

**Comment by geisserf** [comment]
Just to make it clear: the planner is now licensed under the MIT license, apart from a few minor pieces of code that we can't put under this license. More details are in the updated readme and the wiki.
