### ISSUE TITLE
better explanation of failing preconditions

### ISSUE THREAD

**Issue by fdouglis** [prost-planner/prost#128]
(I looked for this issue and couldn't find it -- realized I somehow posted it under rddlsim instead, and amazingly no one commented and said WTF ...  Reposting here.) 

As noted in ssanner/rddlsim#11, I've run into situations where prost will abort in the parser because it thinks that there is no applicable action. I added my own debugging to say which actions passed which preconditions, and could see when all actions failed. Then I had to add debugging to say which preconditions tripped up any given actions. But this is the sort of information that should be generally useful (and I'm sure my own one-off hacks to get that info aren't all that useful, e.g. as a pull request). For instance, to see the human-readable version of the precondition I had to recompile with certain lines changed, save to a separate file, then match them up by hand.

Anything prost can do to make such inconsistencies more explicit, rather than just raising exceptions, will be appreciated! Ideally, I'd like to see prost do the same thing as the verbose rddlsim: I've hit an error, and at the time of the error, the state variables all have the following values, and the following precondition/invariant failed.

**Comment by geisserf** [comment]
Implemented in 3f754f87c27d87b6afe5c075084f179cbd54b3d8.

You can test the behaviour by starting a task with no applicable actions with the rddl-server: `./run-server.py -b experiments/issue-128/` in the benchmark directory. Then, `./prost.py no-applicable-action_inst_mdp__01 [PROST -s 1 -se [IPC2014]]` will show the output that happens if this is encountered during parsing, and `./prost.py no-applicable-action_inst_mdp__02 --parser-options "-trainingSimulations 1" [PROST -s 1 -se [IPC2014]]` shows the output if this happens during search.

**Comment by thomaskeller79** [comment]
Thanks @geisserf!

@fdouglis please let us know if there is further information you'd like to have printed if a state without applicable actions is encountered.

**Comment by fdouglis** [comment]
Thanks for the update.  I had some issues rebuilding (moved to a new system and it was having problems with the cmake ROOT setup and finding the external libraries/includes) but I have now built.  The first example  (error in parsing) looks outstanding.  I hit an exception in the error during search, but I don't actually see info telling me what happened.  There must be some discrepancy in my environment.

**Comment by thomaskeller79** [comment]
> I hit an exception in the error during search, but I don't actually see info telling me what happened. There must be some discrepancy in my environment.

Thanks for testing! I don't like what you are saying though and would like to look into this. Is there any chance you can reproduce this behavior with a RDDL file you are willing to share with us?

**Comment by fdouglis** [comment]
The error was with the new issue-128 RDDL, so that's not it.  There must be something else going on, but I'm not sure what that would be.  

The RDDLSIM server outputs the following.  I assume "premature end of file" means prost exited and the connection dropped. 

> ./run-server.py -b experiments/issue-128/ 
Running benchmark experiments/issue-128/...
Loading: experiments/issue-128/no-applicable-action_mdp.rddl
Loading: experiments/issue-128/no-applicable-action_inst_mdp__02.rddl
Loading: experiments/issue-128/no-applicable-action_inst_mdp__01.rddl
RDDL Server Initialized
Connection from client at address localhost / 127.0.0.1
Client name: prost
Instance requested: no-applicable-action_inst_mdp__02
Updating intermediate variables
Round 1 / 30, time remaining: 1078091
[ Memory usage: 71.77Mb / 106.95Mb = 0.67 ]
[Fatal Error] :-1:-1: Premature end of file.
FATAL SERVER ERROR:
org.xml.sax.SAXParseException; Premature end of file.
org.xml.sax.SAXParseException; Premature end of file.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at rddl.competition.Server.processXMLAction(Server.java:646)
	at rddl.competition.Server.run(Server.java:359)
	at java.base/java.lang.Thread.run(Thread.java:834)

>> TERMINATING TRIAL.

And the prost output looks like this.  It seems to exit w/o any complaint at all?

>Parsing...
Setting number of simulations for training set creation to 1
...finished (0.000917912s).
Instantiating...
    Instantiating variables...
    ...finished (2.00272e-05)
    Instantiating CPFs...
    ...finished (1.21593e-05)
    Instantiating preconditions...
    ...finished (2.59876e-05)
...finished (6.48499e-05s).
Simplifying...
    Simplify formulas (1)...
    ...finished (2.00272e-05)
    Compute inapplicable action fluents (1)...
    ...finished (0.00827098)
    Compute relevant action fluents (1)...
    ...finished (5.96046e-06)
    Determine FDR action fluents (1)...
    ...finished (0.012506)
    Simplify formulas (2)...
    ...finished (2.71797e-05)
    Compute inapplicable action fluents (2)...
    ...finished (0.00429201)
    Compute relevant action fluents (2)...
    ...finished (2.86102e-06)
    Determine FDR action fluents (2)...
    ...finished (1.90735e-06)
    Compute actions (2)...
    ...finished (0.0119259)
    Approximate domains (2)...
    ...finished (6.48499e-05)
    Initialize action states...
    ...finished (0.00637984)
...finished (0.0435619s).
Determinizing...
...finished (2.5034e-05s).
Generating hash keys...
    Preparing state hash keys...
    ...finished (1.90735e-06)
    Preparing Kleene state hash keys...
    ...finished (2.14577e-06)
    Preparing hash keys of evaluatables...
    ...finished (1.00136e-05)
...finished (1.90735e-05s).
Precomputing evaluatables...
...finished (6.31809e-05s).
Analyzing task...
    Determining task properties...
    ...finished (9.53674e-07)
    Calculating min and max reward...
    ...finished (9.53674e-07)
    Performing random walks...
    ...finished (0.000225067)
    Creating training set...
Creating training set with 10 candidates.
    ...finished (4.05312e-06)
...finished (0.000237942s).
Writing output for instance no-applicable-action_inst_mdp__02 to ./parser_out_1394795 ...
...finished (0.0026989s).
PROST parser complete running time: 0.00270391s
THTS heuristic IDS: Setting max search depth to: 10
--------------------------------------------
>>> STARTING ROUND 1 -- REMAINING TIME 1078s
>--------------------------------------------
>Planning step 1/10 in round 1/30
>Current state: | 1 0 1 1 1 1 0 0 0 0 
>./search-release no-applicable-action_inst_mdp__02 --parser-options "-trainingSimulations 1" "[PROST -s 1 -se [IPC2014]]"

Does this help?
