### ISSUE TITLE
Experiment tracking

### ISSUE THREAD

**Issue by GMMDMDIDEMS** [prost-planner/prost#137]
Hi, I wanted to test the performance of PROST on several RDDL instances as automatically as possible, also by changing some parameters such as timeout or search depth.

Is there a setup for tracking the experiments and the PROST parameters used in each case? So for example you have the name of the RDDL instance, the PROST parameters used and the reward achieved.

**Comment by thomaskeller79** [comment]
I am using [prostlab](https://github.com/prost-planner/prostlab) to perform experiments with the prost planner, and prostlab fits your described requirements (i.e., you can run differently parametrized planner instances on a benchmark set). prostlab is not documented well (the exception is [this page](https://github.com/prost-planner/prost/wiki/Evaluation) in the prost documentation), but it's a fork of the lab experiment framework which has a great [documentation](https://lab.readthedocs.io/en/stable/). If these pointers aren't sufficient to setup your experiment, please feel free to contact me directly via email at tho.keller@unibas.ch (or use this issue tracker if you prefer).
