### ISSUE TITLE
Segmentation fault if reward lock detection is used

### ISSUE THREAD

**Issue by thomaskeller79** [prost-planner/prost#77]
**[Original report](https://bitbucket.org/tkeller/prost/issue/77) by David Speck (Bitbucket: [557058:11781bb6-5488-4b73-b91c-b3528daa862c](https://bitbucket.org/557058:11781bb6-5488-4b73-b91c-b3528daa862c), GitHub: [speckdavid](https://github.com/speckdavid)).**

----------------------------------------

In some instances, a segmentation fault occurs when reward lock detection is set/unset as a parameter. If the planner decides whether it is necessary to detect reward locks, this is most likely not the case. Here are two calls where a segmentation fault occurs.

`./prost.py tamarisk_inst_mdp__1 "[PROST -s 1 -se [THTS -act [UCB1] -out [MC] -backup [MC] -init [Expand -h [IDS -sd 15] -iv 5 -hw 1.0] -ndn H -sd 15 -rld 1 -crl 1]]"`

`./prost.py tamarisk_inst_mdp__1 "[PROST -s 1 -se [THTS -act [UCB1] -out [MC] -backup [MC] -init [Expand -h [IDS -sd 15] -iv 5 -hw 1.0] -ndn H -sd 15 -rld 1 -crl 0]]"`

**Comment by speckdavid** [comment]
This issue has been resolved in da59028.
