### ISSUE TITLE
Update scripts to python 3

### ISSUE THREAD

**Issue by thomaskeller79** [prost-planner/prost#78]
After issue-64 has been merged, there will be the following python scripts in the prost repo that should be made compatible with python 3:
- build.py
- build_configs.py
- prost.py
- testbed/additional_filters.py
- testbed/benchmark_suites.py
- testbed/experiment.py
- testbed/ipc_scores.py
- testbed/parser.py
- testbed/prost_plots.py
- testbed/reports.py
- testbed/standard-report.py

Most of these should already be compatible with python 3.

**Comment by thomaskeller79** [comment]
@abcorrea You touched most of these in the last few months, how many of these scipts are not python 3 compatible?

**Comment by abcorrea** [comment]
The ones that for sure *are not*:

- ```testbed/experiment.py```
- ```testbed/prost_plots.py```
- ```testbed/reports.py```

The ones that are executable (e.g., ```build.py```) would probably be better if we called ```python3``` as the interpreter (first line of the file).

**Comment by thomaskeller79** [comment]
This issue has been merged into issue #94 but not yet into the master branch. We'll close this one along with issue #94 when both are merged.

**Comment by thomaskeller79** [comment]
This issue has been merged along with issue +94 in 12dfe8b00b2f9a7f9b6a61a03ce529bb26f4505a.
