### ISSUE TITLE
Update README section about analyze scripts

### ISSUE THREAD

**Issue by geisserf** [prost-planner/prost#79]
Now that we have removed the analyze scripts and added support for the lab framework we should update the corresponding section in the README (===[ Compare your search engine ]===).

An easy option would be to copy the text from the [wiki](https://github.com/prost-planner/prost/wiki/Evaluation). Alternatively, we could extend the wiki documentation and then update the README once we have done this.

**Comment by speckdavid** [comment]
Some links should also be updated. For example, the README still refers to the Wiki on bitbucket.

**Comment by geisserf** [comment]
This issue was resolved in commit 424104f.
