### ISSUE TITLE
Provide script to move lab log directories into appropriately named directories

### ISSUE THREAD

**Issue by geisserf** [prost-planner/prost#81]
When experiments are evaluated with lab, lab creates folders called runs-{}, for every 100 runs and it is impossible to see which run corresponds to which configuration without additional commands. This makes it hard to check logs for possible bugs.

As far as I know lab does not intend to change this functionality, so I would like to have a script which automatically moves the logs into appropriate directories (e.g. config/domain/instance).

**Comment by geisserf** [comment]
Example script to use meanwhile:

```
import json
import os
import sys
import shutil
from pathlib import Path


class LogData:

    def __init__(self, config_name, problem):
        self.config = config_name
        self.problem = problem

    def __str__(self):
        return "{}/{}".format(self.config, self.problem)

    def __repr__(self):
        return "{}/{}".format(self.config, self.problem)


def get_log_data(folder):
    """ Parses the static properties file and creates a log data object.
    Every prost run contains a static properties file that has the problem name
    and configuration name stored.
    """
    for dir_path, dir_names, filenames in os.walk(folder):
        for file_name in filenames:
            if file_name != "static-properties":
                continue
            full_file_name = os.path.join(dir_path, file_name)
            with open(full_file_name) as json_file:
                data = json.load(json_file)
                assert("algorithm" in data)
                assert("problem" in data)
                config_name = data["algorithm"].replace(" ", "_")
                return LogData(data["algorithm"], data["problem"])
    return None


def make_log_dict(folder):
    """ Goes through all subfolders, stores the log data, and returns a dict of
    log_data -> folder_path.
    """
    log_dict = dict()
    for dir_path, dir_names, filenames in os.walk(folder):
        for folder in dir_names:
            full_folder_name = os.path.join(dir_path, folder)
            if "static-properties" not in os.listdir(full_folder_name):
                continue
            log_data = get_log_data(full_folder_name)
            if not log_data:
                continue
            log_dict[log_data] = os.path.join(dir_path, folder)
    return log_dict


def copy_logs(source_folder, target_folder):
    """ Moves all logs from the source folder to the target folder, with
    subdirectories according to config_name/problem.
    """
    log_dict = make_log_dict(source_folder)
    print("Copying logs from {} to {}".format(source_folder, target_folder))
    for log_data, log_folder_path in log_dict.items():
        path_name = "{}/{}/{}".format(target_folder, log_data.config,
                                      log_data.problem)
        Path(path_name).mkdir(parents=True, exist_ok=True)
        # copy files from old folder to new
        print(log_data)
        print(log_folder_path)
        for dir_path, dir_names, filenames in os.walk(log_folder_path):
            for file_name in filenames:
                full_file_name = os.path.join(dir_path, file_name)
                print(
                    "Copying log data from {}".format(full_file_name))
                shutil.copy(full_file_name, path_name)


def main(source_folder, target_folder):
    """ Assumes script is called from the current working directory. Copies
    logs from the source folder to the target folder, such that logs for one run
    are in the directory 'target_folder/config_name/problem_name/'.
    """
    cwd = os.getcwd()
    full_source_name = os.path.join(cwd, source_folder)
    full_target_name = os.path.join(cwd, target_folder)
    copy_logs(full_source_name, full_target_name)


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
```

**Comment by thomaskeller79** [comment]
I remember that we discussed this at some point when we found out that you can add a table to a lab report that provides a mapping from config/domain/instance to the the run ID. Is that not an option?

**Comment by geisserf** [comment]
Would it then not also be possible to add a hyperlink to thist able that allows to open the run.out/run.err directly in the browser? I think that would be the best option, then one can easily navigate with the report.

**Comment by thomaskeller79** [comment]
@geisserf I would love that, but that would mean that all the logs must be copied somewhere where they can be accessed via a browser. That's too much data unfortunately.

**Comment by geisserf** [comment]
Ah, that is right, I forgot that the logs are only stored locally. Maybe the table mapping is a sufficient solution then, I would have to try it out though.

**Comment by thomaskeller79** [comment]
@abcorrea could you adapt the reports.py script in the testbed folder such that the report.html includes this information? Afterwards, you can create a pull request for this issue (@geisserf, speak up if you want something else added here).

**Comment by abcorrea** [comment]
I created a branch for that, but then I realized that this attribute is already in the default attributes used to produce ```report.html```. Could you check if this is enough, @geisserf?

**Comment by thomaskeller79** [comment]
@abcorrea I can verify that the run_dir is already in the reports.html. Thanks for having a look! 

@geisserf from my side we can close this issue, what about you?

**Comment by geisserf** [comment]
@thomaskeller79 I can't find it in the logs that David sent around, is that because he filtered these out?

**Comment by abcorrea** [comment]
Did he also send the properties file? It should be contained in the properties file as well.

**Comment by geisserf** [comment]
Yes, it is also not part of the properties file.

**Comment by abcorrea** [comment]
This is a bit weird because you can filter the something from the report, but no from the properties file (a priori). In ```experiments.py``` we explicitly set ```properties['run_dir'] = run_dir``` in the line number 236 (```master``` branch). I can check it in more detail tomorrow (I do not have any Prost experiment here and the grid is full right now), but it would be good to confirm if @speckdavid  ran the ```experiments.py``` as it is or if there was anything different.

**Comment by geisserf** [comment]
He mentions that he uses the 'new' experiment.py script, so maybe it is an issue with that. I think David is currently on his trip to the USA and then on vacation, but maybe he has time to give a brief comment here.

**Comment by thomaskeller79** [comment]
I ran report.py with the latest version of lab on the data he sent around and a report.html was created, including the run_dir entry. The used information is in the 'static-properties' file in the data folder. You can look at the report here (I cannot paste the report here, html files are apparently not allowed):

http://ai.cs.unibas.ch/_tmp_files/tkeller/report.html

**Comment by geisserf** [comment]
Ah, I did not look into static-properties. Then he probably filtered these out. I am fine with that then, it seems to be alright to use it on a second screen to navigate the directories.

**Comment by thomaskeller79** [comment]
@geisserf the future of this issue is all up to you then ;) from my side, feel free to close it...
