### ISSUE TITLE
Issues with iterative deepening search and timeout restrictions

### ISSUE THREAD

**Issue by geisserf** [prost-planner/prost#92]
The IDS heuristic checks in each iteration if it violates the strict termination timeout, and reduces its search depth in this case (see `iterative_deepening_search.cc::moreIterations(int const& stepsToGo)`). This was done back then for IPPC2014, since once caching is disabled IDS might require more time (due to a more costly transition function calculation) than what it used to do during learning (where the search depth is determined). Back then, we used to switch IDS for a minimum lookahead search (MLS) once the search depth was too low, but this was removed in issue #23 .

 There a couple of issues with the moreIterations function:

- the first condition is wrong (` if (stepsToGo == 1)`), it should be maxSearchDepth instead
- If the timeout is violated multiple times and we are already at a search depth of 1, then the log is spammed with timeout violation, which can lead to very large log sizes
- In general, once we have a search depth of 1 (which is already trivial) it may still happen that computing the heuristic is too costly. Although it is unlikely that the planner performs well on such a domain, it would make more sense to exchange the heuristic for a constant zero heuristic in this case, to guarantee that we satisfy time constraints.

**Comment by thomaskeller79** [comment]
In initializer.cc, we replace a heuristic with UniformEvaluationSearch if its maxSearchDepth is 1. We could do this check periodically and replace the heuristic under the same condition to resolve this issue.

**Comment by thomaskeller79** [comment]
This issue has been merged into issue #94 but not yet into the master branch. We'll close this one along with issue #94 when both are merged.

**Comment by thomaskeller79** [comment]
This issue has been merged along with issue +94 in 12dfe8b00b2f9a7f9b6a61a03ce529bb26f4505a.
