### ISSUE TITLE
Modify CMake debug compiler options

### ISSUE THREAD

**Issue by geisserf** [prost-planner/prost#93]
Some of the compiler options for the debug mode are outdated in make_modules/ProstMacros.cmake:

- `set(CMAKE_CXX_FLAGS_DEBUG "-fprofile-arcs -ftest-coverage -lgcov")`: These were introduced when we had a code coverage module, which no longer exists.
- `set(CMAKE_CXX_FLAGS_TEST "-I../test -DGTEST_HAS_PTHREAD=0")`: This was required for gtest, which is no longer used.
- `  set(CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS} -O3 -lgcov")`: lgcov was also for code coverage
- `  set(CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS} -O3 -lgcov")`: as above

I would also like to propose to add `-fmax-errors=5` to debug mode, which terminates compilation after 5 error messages. Personally I do not see much use in seeing more than the first 5 error messages, and this reduces scrolling through heaps of error messages when implementing new features.

**Comment by thomaskeller79** [comment]
Issue has been resolved in commit e2af290493e71e8d1d08cbbed13339e95aca24c3
