### ISSUE TITLE
Refactor experiment.py

### ISSUE THREAD

**Issue by thomaskeller79** [prost-planner/prost#94]
I'd like to propose some more changes to the experiment.py script. Because of issue #83, I don't want to put too much work into the script, but I am currently unable to run an experiment on the grid, so some work is required anyway. I'd like to additionally change the following things:

- set a soft memory limit with ulimit
- convert to python 3
- in python 3, the result of git log is of type byte rather than string, which has to be converted
- I propose to replace the git log to determine the revision with git rev-parse --short HEAD. The large directory name is ugly
- I'd like to pass the -ipc2018 command line argument to the parser. Unfortunately, this means this issue has a blocking dependency with issue #91.

**Comment by speckdavid** [comment]
I totally agreed with points 2-5. What ist the idea of a soft limit (point 1)? The planner should not directly be killed once a certain memory limit is reached?

**Comment by thomaskeller79** [comment]
This was suggested by @abcorrea [here](https://github.com/prost-planner/prost/issues/82#issuecomment-580200576) but I am not 100% sure if this helps. If you meet him in NY, you could discuss this directly.

**Comment by thomaskeller79** [comment]
@abcorrea : Why are you using raw strings in the patterns in parser.py? If I am not mistaken, this means that the escape characters are no longer escape characters, so you are actually looking for strings that end with "\n" (rather than newline)? 

Also, is the "if __name__ == '__main__':" really correct there? Isn't this part necessary if the parser is added with add_parser()?

**Comment by thomaskeller79** [comment]
I finally managed to get an experiment running and generate a [report](https://ai.dmi.unibas.ch/_tmp_files/tkeller/report.html), but only with 10 runs and 1 second timeout. I'm not sure the results make any sense, and the navigation results of the IPC2014 config in particular worries me. However, the amount of output produced by the planners is way too high at the moment, and I'd like to get rid of that before analyzing results in detail. For this issue, it's just important that everything seems to be working now.

**Comment by geisserf** [comment]
I do not have the log files, but if we changed nothing for this issue on the output, then the problem is that we print the estimation of all QValues. Since many of the larger tasks have often several thousands of actions this leads to very large log files. The fix we used for the IPC18 was to just not print the QValue estimation of every action, we could do the same here.

**Comment by speckdavid** [comment]
I just spoke to @abcorrea  about a soft memory limit with ulimit.  If a task uses too much memory, it is currently being hard killed by slurm, which can lead to error messages that are then written to the slurm error file. If you use ulimit with a slightly lower limit than slurm, the process will terminate correctly and all relevant messages can be written to the appropriate run.err file. This may also be possible for timeouts.

Do you think it's worth it?

**Comment by thomaskeller79** [comment]
This issue has been resolved in 12dfe8b00b2f9a7f9b6a61a03ce529bb26f4505a.
