### ISSUE TITLE
Introduce different log levels

### ISSUE THREAD

**Issue by thomaskeller79** [prost-planner/prost#95]
A small experiment with just 10 runs per instance and 2 planner configurations already produces approx. 40GB of output. We must significantly reduce this for experiments, but also be able to enable all the output we need.

**Comment by geisserf** [comment]
I propose that we use a sophisticated logging mechanism that allows us to separate logging at least into  debug, information, and benchmark modes. There already exist several tools for logging (e.g. Boost.Log), so we should look into what makes the most sense for us.

**Comment by geisserf** [comment]
Implemented in 1862d5ab6476ad3f2c46383e9cb1df6472fe19e3.
