### ISSUE TITLE
Archiving of experiment results

### ISSUE THREAD

**Issue by speckdavid** [prost-planner/prost#96]
It would be desirable to have a script that archives experiment results. This is especially important because we use symbolic links, which should be handled correctly to keep the required memory as low as possible.

**Comment by thomaskeller79** [comment]
Does anything speak against removing the symlinks at the end of an experiment?

**Comment by speckdavid** [comment]
Yes, we can close this issue. This was mainly due to the old experimental setup. I will close the issue.
