### ISSUE TITLE
search depth of iterative deepening search can not be set via -sd parameter

### ISSUE THREAD

**Issue by geisserf** [prost-planner/prost#98]
Passing -sd to IDS does nothing. This is particular important because the IPC2011 configuration explcitly uses the IDS with a search depth of 15, which currently has no effect.

**Comment by thomaskeller79** [comment]
I cannot reproduce this. Remember that -sd set the *max* search depth to some value, not the search depth that is actually used. If I set this to 15 in elevators 2 via

`./prost.py elevators_inst_mdp__2 [PROST -s 1 -se [THTS -act [UCB1] -out [UMC] -backup [PB] -init [Expand -h [IDS -sd 15]]]]`

IDS learns a max search depth of 15. If I omit the -sd 15 parameter of IDS, IDS learns a max search depth of 40.

**Comment by geisserf** [comment]
Ah, I had the impression that this was used to set the minimum search depth. Then this issue is not relevant.
